# Generated by Django 5.0.7 on 2024-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3,5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('0', '0'), ('0.5', '0.5')], max_length=255, null=True),
        ),
    ]
