# Generated by Django 5.0.7 on 2024-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookrating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisheddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
